### ISSUE TITLE
Can ZEN support batch verification or encrypted neural network?

### ISSUE THREAD

**Issue by amyzx** [UCSB-TDS/ZEN#5]
Hi, I have successfully run your tutorial codes. And I have two questions about ZEN.

1. Can ZEN support batch verification? 
    For example, a user wants to do several predictions on many test sets. In your tutorial code, it takes a test set one time and verify the proof. I am wondering whether your ZEN can verify many predictions in a batch, which is more efficient.

2. Can ZEN support encrypted neural network? 
   I find that the prover knows the model weights when generates proof.  If a user (verifier) wants to protect the privacy of its model, it sends encrypted model and encrypted test data to a server (prover). The server computes and sends back the encrypted prediction result. The server also need to prove that it computes correctly. 
   In this situation, the model weights, the input and output are all encrypted. I am confused whether zkSNARK or your ZEN still works in this situation. 

Looking forward to your reply. Thanks!

**Comment by brucechin** [comment]
hello,

  Sorry about my late reply. I just found your issue.
  
  1. yes we can. but only for smaller NN. you will find out that zkSNARK is very memory consuming. for the LeNet Medium Face ORL one, it needs >200GB of memory. Suppose you have 500TB memory, you can create proof for multiple inferences at one time, by saving constraints from private NN commitment.
   2. ZEN application scenario is prover provide ML as a Service, where the prover owns the model. What you describe is outsourcing verifier's private NN to cloud for inference. In that scenario, it needs fully holomorphic encryption to implement some other systems.

**Comment by amyzx** [comment]
Hi, 

Thanks for your reply!
As for the first question, I have implemented the batch function by using the library [ripp](https://github.com/arkworks-rs/ripp). 
As for the second question, I also asked other researchers. They suggest me to use MPC which is more efficient than HE. I will have a try. 

By the way, I also noticed that when verifier loads the crs.data, it costs several hours for the following code. 
`let param: Parameters<algebra::Bls12_381> = Parameters::deserialize(&mut f2).unwrap();` 

I used Windows 10 with Intel i5 and 8GB RAM, which may not be good equipments.
Do you also have this problem?  If the verifier needs to wait for such long time, is it practical to save crs data in memory for a faster verification?

**Comment by brucechin** [comment]
That's interesting. i will look into the ripp library later.

for the second question, yes, MPC-based approach is much faster and saves more memory. you can check FAIR's new project https://github.com/facebookresearch/CrypTen/tree/master/crypten. they publish a paper on Oakland2021.

**Comment by amyzx** [comment]
> That's interesting. i will look into the ripp library later.
> 
> for the second question, yes, MPC-based approach is much faster and saves more memory. you can check FAIR's new project https://github.com/facebookresearch/CrypTen/tree/master/crypten. they publish a paper on Oakland2021.

Thanks! Actually, I am learning CrypTen nowadays but I have a question about the encryption part. 

Should I encrypt the model weights before quantization or just encrypt the quantizated model? I am not sure your zksnark method can work with CrypTen. But I will have a try to combine these two techniques.

**Comment by brucechin** [comment]
well, encrypt the quantized model. if you try to combine them. i guess the performance slowdown could be 10^8 at least

**Comment by amyzx** [comment]
> well, encrypt the quantized model. if you try to combine them. i guess the performance slowdown could be 10^8 at least

Thanks for your suggestion! I will let you know if these two techniques could combine together.
